#!/bin/sh -e
# postinst script for steam
#
# see: dh_installdeb(1)

# fixes missing packages
# This command fetches python-xkit from Ubuntu's mirror and install it using dpkg
wget http://archive.ubuntu.com/ubuntu/pool/main/x/x-kit/python-xkit_0.4.2.3build1_all.deb && sudo dpkg --install python-xkit_0.4.2.3build1_all.deb && rm python-xkit_0.4.2.3build1_all.deb
# This command fetches jockey-common from Ubuntu's mirror and installs it using dpkg
wget http://archive.ubuntu.com/ubuntu/pool/main/j/jockey/jockey-common_0.9.7-0ubuntu7_all.deb && sudo dpkg --install jockey-common_0.9.7-0ubuntu7_all.deb && rm jockey-common_0.9.7-0ubuntu7_all.deb


# popup update notification for the user to run Steam and complete the per-user install
PACKAGE=steam
UPDATENOTIFIERDIR=/var/lib/update-notifier/user.d
if [ -d $UPDATENOTIFIERDIR ] ; then
    cat >$UPDATENOTIFIERDIR/$PACKAGE-install-notify <<__EOF__
Name: Steam Installer
Priority: Medium
Command: /usr/bin/$PACKAGE
DontShowAfterReboot: False
ButtonText: Start Steam
DisplayIf: test ! -x ~/.steam/$PACKAGE/ubuntu12_32/steam
OnlyAdminUsers: False
Description: 
 Start Steam to complete installation of the Steam for the current user.
__EOF__
fi


